/// Generated by AssetsRefGenerator on 2022/12/06
class Res {
  static const String api_empty = "assets/anim/api_empty.json";
  static const String api_error = "assets/anim/api_error.json";
  static const String ar = "assets/lang/ar.json";
  static const String delivery = "assets/anim/delivery.json";
  static const String empty_cart = "assets/anim/empty_cart.json";
  static const String en = "assets/lang/en.json";
  static const String filter = "assets/images/filter.png";
  static const String following = "assets/images/following.png";
  static const String hands = "assets/images/hands.png";
  static const String logo = "assets/images/logo.png";
  static const String marker = "assets/images/marker.png";
  static const String maxresdefault = "assets/images/maxresdefault.jpg";
  static const String nodata = "assets/images/nodata.png";
  static const String onboarding = "assets/images/onboarding.png";
  static const String person_avatar_test = "assets/images/person_avatar_test.png";
  static const String placeholder = "assets/images/placeholder.png";
  static const String plus = "assets/images/plus.png";
  static const String search = "assets/images/search.svg";
  static const String settings = "assets/images/settings.svg";
  static const String splash = "assets/images/splash.png";
  static const String success = "assets/anim/success.json";
  static const String success_result = "assets/images/success_result.png";
  static const String successQuiz = "assets/images/successQuiz.png";
  static const String test_ielts = "assets/images/test_ielts.png";
  static const String toefl_course_featured = "assets/images/toefl-course-featured.jpg";
}
